### ISSUE TITLE
support using commit SHA1 as version

### ISSUE THREAD

**Issue by ldegen** [ErickKramer/ripvcs#13]
Hi @ErickKramer 

as far as I can tell (me no speak golang ;-)), I can currently use any ref as value for the `version` field in my repos file, so branch names, tags, symbolic refs: all no problem. But in many situations, it would be really helpful if I could directly refer to the SHA1 digest of a commit object.

Do you think that would be possible / hard to do?

Cheers,
Lukas

**Comment by ErickKramer** [comment]
Hi @ldegen, that should be supported already in version [v0.1.3](https://github.com/ErickKramer/ripvcs/releases/tag/v0.1.3)

**Comment by ldegen** [comment]
For anyone else coming here: Turns out it *is* in fact working for commands like `import`. It is just not working for `validate` it seems.
