### ISSUE TITLE
import: `--skip` should probably be the default behavior?

### ISSUE THREAD

**Issue by ldegen** [ErickKramer/ripvcs#9]
Hi @ErickKramer,

it seems that the current default behavior of the `import` command when a repository / working dir of the same name already exists is to delete the existing directory before cloning anew.

This turned out to be somewhat of a foot gun in my case. I was using `rv import` as part of shell script that I run to make sure all my dependencies are up to date with what ever is specified in the repos files. 

Happy to report, I am up to date now. On the flip side, though, I lost all my local branches, and AFAICS there is no way to recover from that since the repository including the object store and the reflog are all gone.

Ok, yes, I should have RTFM before automating this step. :facepalm: 
Luckily for me, it did not take long until I realized my mistake and I sort of remember the changes I did there - so not too much work is lost. 

Still... I think this should not be the default behavior. Maybe just output an error and exit. Maybe `--skip`. Or maybe something like `rv sync`. Just do something safe by default.

Cheers,
Lukas

**Comment by ErickKramer** [comment]
Thanks for raising this issue. I see what you mean and understand how the consequences of such default behavior are quite destructive.

I was just following the default behavior provided by vcstool, but I do agree that what you are suggesting is the safer approach.

I will replace the `--skip` flag to something like an `--overwrite` (some name will pop-up) to force overwriting the existing repositories.
